#!/usr/bin/env node

import {generateKeyPair, exportJWK} from "jose";

async function main() {
	const { privateKey, publicKey } = await generateKeyPair("EdDSA", { crv: "Ed25519" });
	console.log(`Public key: ${Buffer.from(JSON.stringify(await exportJWK(publicKey))).toString("base64url")}`);
	console.log(`Private key: ${Buffer.from(JSON.stringify(await exportJWK(privateKey))).toString("base64url")}`);
}

main().catch(err => {
	console.error(err);
	process.exit(1);
});
